CREATE TABLE UNIVERSITY.AGERESTRICTION
(
	Id INT CONSTRAINT FK_AGERESTRICTION_ID FOREIGN KEY(Id) REFERENCES UNIVERSITY.RESTRICTION(Id) CONSTRAINT PK_AGERESTRICTION_ID PRIMARY KEY,
	MinAge INTEGER NOT NULL CONSTRAINT CK_AGERESTRICTION_MINAGE CHECK (MinAge > 0)
);

-- DROP TABLE UNIVERSITY.AGERESTRICTION;