CREATE TABLE UNIVERSITY.ATTRACTIONHISTORY
(
	AttractionName VARCHAR(100) NOT NULL,
	HistoryDate DATE NOT NULL,
	[Description] VARCHAR(100) NOT NULL
);
GO

ALTER TABLE UNIVERSITY.ATTRACTIONHISTORY
ADD CONSTRAINT PK_ATTRACTIONHISTORY_ATTRACTIONNAME_HISTORYDATE
PRIMARY KEY (AttractionName, HistoryDate);

-- DROP TABLE UNIVERSITY.ATTRACTIONHISTORY;