CREATE TABLE UNIVERSITY.ATTRACTION
(
	[Name] VARCHAR(100) CONSTRAINT PK_ATTRACTION_NAME PRIMARY KEY,
	[Description] VARCHAR(100) NOT NULL,
	BuildDate DATE CONSTRAINT CK_ATTRACTION_BUILDDATE CHECK (BuildDate <= CAST(GETDATE() AS DATE)) CONSTRAINT DF_ATTRACTION_BUILDDATE DEFAULT CAST(GETDATE() AS DATE),
	Cost INTEGER NOT NULL CONSTRAINT CK_ATTRACTION_COST CHECK (Cost > 0),
	Manager CHAR(9) NOT NULL CONSTRAINT FK_ATTRACTION_MANAGER FOREIGN KEY(Manager) REFERENCES UNIVERSITY.EMPLOYEE(Ssn),
	DateStarted DATE NOT NULL,
	IsAgeRestricted BIT NOT NULL CONSTRAINT DF_ATTRACTION_ISAGERESTRICTED DEFAULT 0
);

-- DROP TABLE UNIVERSITY.ATTRACTION