CREATE TABLE UNIVERSITY.RESTRICTION
(
	Id INT CONSTRAINT PK_RESTRICTION_ID PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
	[Description] VARCHAR(100) NOT NULL,
	AttractionName VARCHAR(100) NOT NULL CONSTRAINT FK_RESTRICTION_ATTRACTIONNAME FOREIGN KEY(AttractionName) REFERENCES UNIVERSITY.ATTRACTION([Name]),
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL
);

GO

ALTER TABLE UNIVERSITY.RESTRICTION ADD CONSTRAINT
CK_RESTRICTION_STARTDATE_ENDDATE CHECK (StartDate <= EndDate);

GO

-- DROP TABLE UNIVERSITY.RESTRICTION;