CREATE TABLE UNIVERSITY.RIDE
(
	AttractionName VARCHAR(100) NOT NULL CONSTRAINT FK_RIDE_ATTRACTIONNAME FOREIGN KEY(AttractionName) REFERENCES UNIVERSITY.ATTRACTION([Name]),
	RiderEmail VARCHAR(256) NOT NULL CONSTRAINT FK_RIDE_RIDEREMAIL FOREIGN KEY(RiderEmail) REFERENCES UNIVERSITY.RIDER(Email),
	BoardingTime DATETIME NOT NULL
);
GO
ALTER TABLE UNIVERSITY.RIDE ADD CONSTRAINT PK_RIDE_ATTRACTIONNAME_RIDEREMAIL_BOARDINGTIME
PRIMARY KEY (AttractionName, RiderEmail, BoardingTime);

-- DROP TABLE UNIVERSITY.RIDE;