CREATE TABLE UNIVERSITY.RIDER
(
	Email VARCHAR(256) CONSTRAINT PK_RIDER_EMAIL PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Height INTEGER NOT NULL CONSTRAINT CK_RIDER_HEIGHT CHECK(Height > 0),
	Tickets INTEGER NOT NULL CONSTRAINT CK_RIDER_TICKETS CHECK(Tickets >= 0) CONSTRAINT DF_RIDER_TICKETS DEFAULT 5
);

-- DROP TABLE UNIVERSITY.RIDER;